@startuml
class PlantillasRonda #lightgreen {
}
class CamposRonda #lightgreen {
}
class Horarios #lightgreen {
  id: int;
  dia: int;
  tipoRecurrencia: int;
  hora: Date;
  fechaInicio: Date;
  fechaFin: Date;
}
class CamposRondaPlantillaRonda #lightgreen {
  
}
PlantillasRonda --> CamposRondaPlantillaRonda
CamposRonda --> CamposRondaPlantillaRonda
PlantillasRonda --> Horarios
PlantillasRonda --> Rondas
Rondas --> ValoresCamposRonda
Rondas --> LecturasTag
EstadosRonda --> Rondas
CamposRonda --> ValoresCamposRonda
CamposRonda --> ListaRonda
TiposCamposRonda --> CamposRonda
UnidadesDeMedida --> CamposRonda
Equipamientos --> CamposRonda
Equipamientos -- ValoresCamposManiobra
Equipamientos --> FallaEquipamiento
Sistemas --> Equipamientos
Sistemas --> FallaSistema
Plantas --> Sistemas
CamposManiobra --> ValoresCamposManiobra
PlantillasManiobra --> CamposManiobra
PlantillasManiobra --> GuiasManiobra
GuiasManiobra --> ValoresCamposManiobra
Personas --> Rondas
Usuarios --> Personas
Perfiles --> Personas
Perfiles --> Permisos
Objetos --> Permisos
Tags --> Sistemas
Tags --> LecturasTag
NotificacionesFalla --> ValoresCamposRonda
NotificacionesFalla --> HistorialEstadosFalla
TiposFalla --> NotificacionesFalla
EstadosFalla --> NotificacionesFalla
@enduml