"use strict";
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : new P(function (resolve) { resolve(result.value); }).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
Object.defineProperty(exports, "__esModule", { value: true });
require("reflect-metadata");
const typeorm_1 = require("typeorm");
const User_1 = require("./entity/User");
const Profile_1 = require("./entity/Profile");
const PermissionWS_1 = require("./entity/PermissionWS");
const HTTPMethod_1 = require("./entity/HTTPMethod");
const Report_1 = require("./entity/Report");
const JoinReport_1 = require("./entity/JoinReport");
const JoinType_1 = require("./entity/JoinType");
const JoinReportRepository_1 = require("./repository/JoinReportRepository");
const TipoFallaRepository_1 = require("./repository/TipoFallaRepository");
const TipoFalla_1 = require("./entity/TipoFalla");
typeorm_1.createConnection().then((connection) => __awaiter(this, void 0, void 0, function* () {
    let jt = new JoinType_1.JoinType();
    jt.id = 1;
    jt.description = "left";
    yield connection.manager.save(jt);
    jt.id = 2;
    jt.description = "inner";
    yield connection.manager.save(jt);
    let r2 = new Report_1.Report();
    r2.id = 1;
    r2.from = "CampoManiobra";
    r2.entityAlias = "CampoManiobra";
    r2.description = "Recuperar campos maniobra con nombre de planta";
    r2.where = "CampoManiobra.plantillaGuiaManiobraId = :plantillaGuiaManiobraId";
    yield connection.manager.save(r2);
    let jr = new JoinReportRepository_1.JoinReportRepository();
    let jr2 = new JoinReportRepository_1.JoinReportRepository();
    let j = new JoinReport_1.JoinReport();
    j.joinColumn = "CampoManiobra.sistema";
    j.joinAlias = "sistema";
    j.report = r2;
    j.joinTypeId = 1;
    j.id = 1;
    yield jr.save(j);
    let j2 = new JoinReport_1.JoinReport();
    j2.joinColumn = "sistema.planta";
    j2.joinAlias = "planta";
    j2.report = r2;
    j2.joinTypeId = 1;
    j2.id = 2;
    yield jr2.save(j2);
    const get = new HTTPMethod_1.HTTPMethod();
    const post = new HTTPMethod_1.HTTPMethod();
    const patch = new HTTPMethod_1.HTTPMethod();
    const deleteM = new HTTPMethod_1.HTTPMethod();
    get.name = "get";
    get.id = 1;
    post.name = "post";
    post.id = 2;
    patch.name = "patch";
    patch.id = 3;
    deleteM.name = "deleteM";
    deleteM.id = 4;
    yield connection.manager.save(get);
    yield connection.manager.save(post);
    yield connection.manager.save(deleteM);
    yield connection.manager.save(patch);
    let permiso = new PermissionWS_1.PermissionWS();
    permiso.id = 1;
    permiso.httpMethod = get;
    permiso.servicePath = "^(/entities/users/([0-9]+/)?)$";
    permiso.description = "Recuperar Usuarios";
    yield connection.manager.save(permiso);
    permiso.id = 2;
    permiso = new PermissionWS_1.PermissionWS();
    permiso.httpMethod = deleteM;
    permiso.servicePath = "^(/entities/users/)$";
    permiso.description = "Eliminar Usuarios";
    yield connection.manager.save(permiso);
    permiso.id = 3;
    permiso = new PermissionWS_1.PermissionWS();
    permiso.httpMethod = patch;
    permiso.servicePath = "^(/entities/users/[0-9]+/)$";
    permiso.description = "Modificar Usuarios";
    yield connection.manager.save(permiso);
    permiso.id = 4;
    permiso = new PermissionWS_1.PermissionWS();
    permiso.httpMethod = post;
    permiso.servicePath = "^(/entities/users/)$";
    permiso.description = "Crear Usuarios";
    yield connection.manager.save(permiso);
    let permisoToProfile1 = new PermissionWS_1.PermissionWS();
    permisoToProfile1.id = 1;
    let permisoToProfile2 = new PermissionWS_1.PermissionWS();
    permisoToProfile2.id = 2;
    const adminProfil = new Profile_1.Profile();
    adminProfil.id = 1;
    adminProfil.name = "admin";
    yield connection.manager.save(adminProfil);
    const userProfile = new Profile_1.Profile();
    userProfile.id = 2;
    userProfile.name = "userProfile";
    userProfile.permissionsWS = [permisoToProfile1, permisoToProfile2];
    userProfile.reportAvailable = [r2];
    yield connection.manager.save(userProfile);
    const adminUser = new User_1.User();
    adminUser.id = 1;
    adminUser.password = "123456";
    adminUser.name = "admin";
    adminUser.username = "admin";
    adminUser.dni = "123456";
    adminUser.lastName = "super";
    adminUser.profile = adminProfil;
    adminUser.fileNumber = "123";
    yield connection.manager.save(adminUser);
    const standardUser = new User_1.User();
    standardUser.id = 2;
    standardUser.password = "123456";
    standardUser.name = "lucas";
    standardUser.username = "lsegura";
    standardUser.dni = "prueba";
    standardUser.lastName = "segura";
    standardUser.fileNumber = "123";
    standardUser.profile = userProfile;
    yield connection.manager.save(standardUser);
    let tr = new TipoFallaRepository_1.TipoFallaRepository();
    let tipoFalla1 = new TipoFalla_1.TipoFalla();
    tipoFalla1.id = 1;
    tipoFalla1.nombre = "Detectado";
    tipoFalla1.posicion = 1;
    let tipoFalla2 = new TipoFalla_1.TipoFalla();
    tipoFalla2.id = 2;
    tipoFalla2.nombre = "En reparación";
    tipoFalla2.posicion = 2;
    let tipoFalla3 = new TipoFalla_1.TipoFalla();
    tipoFalla3.id = 3;
    tipoFalla3.nombre = "Solucionado";
    tipoFalla3.posicion = 3;
    yield tr.save(tipoFalla1);
    yield tr.save(tipoFalla2);
    yield tr.save(tipoFalla3);
    /*let perfil = new Profile()
    perfil.id = 1
    connection.manager
      .createQueryBuilder()
      .relation(Profile, "permissionsWS")
      .of(perfil)
      .add(permiso);*/
})).catch(error => console.log(error));
//# sourceMappingURL=load.js.map